### PR TITLE
star alignment fixed

### PR DESCRIPTION
**Pull request by joshpitzalis**

### CODE REVIEW

**Comment by rjmk** [comment]
could you comment auth back in?

**Comment by joshpitzalis** [comment]
done. sorry about that.

**Comment by rjmk** [comment]
no problem.

not sure what's failing on your tests. If they pass locally, try adding a comment or something to trigger a rerun (pretty sure there's a better way to trigger a rerun, but that way works)

**Comment by joshpitzalis** [comment]
this is a rerun comment

**Comment by rjmk** [comment]
AWEEEEESOME

**Pull request merged**
